/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
 * This code modified from sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pwd.h>
#include <rpc/rpc.h>
#include "ssnfs.h"

CLIENT *clnt;

void ssnfsprog_1(char *host) {
    clnt = clnt_create(host, SSNFSPROG, SSNFSVER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
}

int Open(const char *filename_to_open) {
    open_output *outp;
    open_input open_file_1_arg;
    memset(&open_file_1_arg, 0, sizeof(open_input));

    // 获取用户名并复制到结构中
    strncpy(open_file_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    open_file_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';

    // 复制文件名到结构中
    strncpy(open_file_1_arg.file_name, filename_to_open, FILE_NAME_SIZE - 1);
    open_file_1_arg.file_name[FILE_NAME_SIZE - 1] = '\0';

    outp = open_file_1(&open_file_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "Open: call failed");
        exit(1);
    }
    printf("%s\n", outp->out_msg.out_msg_val);
    printf("File descriptor returned is %d\n", outp->fd);
    return outp->fd;
}

void Close(int fd) {
    close_output *outp;
    close_input close_file_1_arg;
    memset(&close_file_1_arg, 0, sizeof(close_input));

    strncpy(close_file_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    close_file_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';
    close_file_1_arg.fd = fd;

    outp = close_file_1(&close_file_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "Close: call failed");
        exit(1);
    }
    printf("%s\n", outp->out_msg.out_msg_val);
}

void Delete(const char *filename_to_delete) {
    delete_output *outp;
    delete_input delete_file_1_arg;
    memset(&delete_file_1_arg, 0, sizeof(delete_input));

    strncpy(delete_file_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    delete_file_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';
    strncpy(delete_file_1_arg.file_name, filename_to_delete, FILE_NAME_SIZE - 1);
    delete_file_1_arg.file_name[FILE_NAME_SIZE - 1] = '\0';

    outp = delete_file_1(&delete_file_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "Delete: call failed");
        exit(1);
    }
    printf("%s\n", outp->out_msg.out_msg_val);
}

void List() {
    list_output *outp;
    list_input list_files_1_arg;
    memset(&list_files_1_arg, 0, sizeof(list_input));

    strncpy(list_files_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    list_files_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';

    outp = list_files_1(&list_files_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "List: call failed");
        exit(1);
    }
    printf("%s\n", outp->out_msg.out_msg_val);
}

void Seek(int fd, int pos) {
    seek_output *outp;
    seek_input seek_position_1_arg;
    memset(&seek_position_1_arg, 0, sizeof(seek_input));

    strncpy(seek_position_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    seek_position_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';
    seek_position_1_arg.fd = fd;
    seek_position_1_arg.position = pos;

    outp = seek_position_1(&seek_position_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "Seek: call failed");
        exit(1);
    }
    printf("%s\n", outp->out_msg.out_msg_val);
}

void Read(int fd, char *buffer, int numbytes) {
    read_output *outp;
    read_input read_file_1_arg;
    memset(&read_file_1_arg, 0, sizeof(read_input));

    strncpy(read_file_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    read_file_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';
    read_file_1_arg.fd = fd;
    read_file_1_arg.numbytes = numbytes;

    outp = read_file_1(&read_file_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "Read: call failed");
        exit(1);
    }

    if (outp->success < 0) {
        printf("%s\n", outp->out_msg.out_msg_val);
    } else {
        memcpy(buffer, outp->buffer.buffer_val, outp->success);
        buffer[outp->success] = '\0';
    }
}

void Write(int fd, char *buffer, int numbytes) {
    write_output *outp;
    write_input write_file_1_arg;
    memset(&write_file_1_arg, 0, sizeof(write_input));

    strncpy(write_file_1_arg.user_name, getpwuid(getuid())->pw_name, USER_NAME_SIZE - 1);
    write_file_1_arg.user_name[USER_NAME_SIZE - 1] = '\0';
    write_file_1_arg.fd = fd;
    write_file_1_arg.numbytes = numbytes;
    write_file_1_arg.buffer.buffer_len = numbytes;
    write_file_1_arg.buffer.buffer_val = buffer; // 直接指向要写入的数据

    outp = write_file_1(&write_file_1_arg, clnt);
    if (outp == NULL) {
        clnt_perror(clnt, "Write: call failed");
        exit(1);
    }
    printf("%s\n", outp->out_msg.out_msg_val);
}

int main(int argc, char *argv[]) {

    if (argc < 2) {
        printf("usage: %s <server_host>\n", argv[0]);
        exit(1);
    }

    ssnfsprog_1(argv[1]);

    int i, j;
    int fd1, fd2;
    char buffer[100];
    fd1 = Open("File1");
    char message[] = "This is a test program for cs570 assignment 4";
    for (i = 0; i < 20; i++) {
        Write(fd1, message, 15);
    }
    Close(fd1);
    fd2 = Open("File1");
    for (j = 0; j < 20; j++) {
        Read(fd2, buffer, 10);
        printf("%s\n", buffer);
    }
    Seek(fd2, 40);
    Read(fd2, buffer, 20);
    printf("%s\n", buffer);
    Close(fd2);
    Delete("File1");

    return 0;
}
